#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	enum class WINMODE { FULL, WIN };
	enum class PROTOTYPE { GAMEOBJECT, COMPONENT };
	enum class RENDER_GROUP { PRIORITY, SHADOW, NONBLEND, NONLIGHT, BLOBSHADOW, DECAL, EFFECT_NONBLEND, EFFECT_BLEND, BLEND, UI, CAMERA, SHADOW_BAKE, GODRAY,WORLD_UI, END };
	enum class DIRECTION { RIGHT, UP, LOOK, POSITION, END };
	enum D3DTRANSFORM { D3DTS_VIEW, D3DTS_PROJ, D3DTS_VIEWPROJ, D3DTS_END };
	enum class MOUSEKEYSTATE { LB, RB, WHEEL, XB, END };
	enum class MOUSEMOVESTATE { X, Y, WHEEL, END };
	enum class LIGHT { DEBUG, DIRECTIONAL, POINT, DIRECTIONAL_TOON, DIRECTIONAL_PBR, SPOTLIGHT, END };
	enum class MODEL { NONANIM, ANIM, PLAYERANIM, END };
	enum class MODELROLE {MASTER,PART,STANDALONE ,END}; //마스터모델 , 파츠모델, 통모델
    enum class NAVPOINT { A, B, C, END };
    enum class NAVLINE { AB, BC, CA, END };
    enum class COLLIDER { SPHERE, AABB, OBB, END };
    enum class TEXTDRAW_SETTING { NORMAL, DIR4, DIR8, END };
    enum class DEFERRED { DEBUG, DIRECTIONAL, POINT, DIRECTIONAL_TOON, DIRECTIONAL_PBR, SPOTLIGHT, COMBINED, COMBINED_CASCADE,
		HDR, HDR_BRIHGTEXTRACT, HDR_SAMPLING, HDR_BLURHORIZONTAL, HDR_BLURVERTICAL, UP_SAMPLING1, HDR_MAPPING, SSAO, SSAO_BLUR, GODRAY_COPY, GODRAY, CAMVELOCITY, CAMMOTIONBLUR, UPSAMPLINGPLUS, END };

	enum class UIANIMTYPE{SCALE,ROTATION,POSITION,ALPHA,UVSCROLL,COLOR,PROGRESS,END};
	enum class EASETYPE {LINEAR,SMOOTH,IMME,SHAKE,CURRENT,BOUNCE,END};
			//IMME-즉시반영

    enum BUFFER_NUMBER {
        BUFFER_CAMERA = 0, BUFFER_OBJECT = 1, BUFFER_LIGHT = 2, BUFFER_MATERIAL = 3, BUFFER_BONES = 4,
        BUFFER_MORPH = 5, BUFFER_COMPUTELOCALANIM = 6, BUFFER_COMPUTEBONE = 7, BUFFER_COMPUTE_PARTICLE = 8, BUFFER_EFFECT = 9, BUFFER_UI=10,
		BUFFER_EMPTY2 = 11, BUFFER_COMPUTEBLENDANIM = 12, BUFFER_FINAL = 13, BUFFER_END
    };

	typedef enum class RSSET { DEFAULT = 0, SOLID_CW = 0, SOLID_CCW = 1, SOLID_SCISSOR, SOLID_NONE, WIRE_CW, WIRE_CCW, WIRE_NONE, SCISSORENABLE, SOLID_SHADOW, RS_END } RSMODE, RSTATE;
	typedef enum class DSSSET { DEFAULT = 0, DEPTH_WRITE = 0, DEPTH = 1, SKY = 1, NODEPTH, STENCIL_WRITE, DECAL_READ, POINTLIGHT, DSS_END } DSSMODE, DSSTATE;
	typedef enum class BSSET { DEFAULT = 0, NONBLEND = 0, BLEND = 1, ADDITIVE, PREMULTIPLIED_ALPHA, DSS_END } BSMODE, BSTATE ;

	enum class WEAPON_TYPE {BAYONET, SWORD, HAMMER, GREATESWORD,HALBERD, WP_END}; //웨폰 타입
	enum class INPUT_DIR { LEFT, RIGHT, UP, DOWN, LEFT_UP, LEFT_DOWN, RIGHT_UP, RIGHT_DOWN ,INPUT_END}; //입력 8방향
	enum class BLOODCODE {FIGHTER,RANGER,CASTER,BLOODCODE_END}; //블러드코드(약간 직업 느낌?)

	// 엔진모드
	enum ENGINEMODE {EDITOR,CLIENT,END};
	// 핫키 입력 모드
	enum class HOTKEY_MODE : _ubyte
	{
		DOWN,	// 누른 순간 1회 발동
		PRESS,	// 누르고 있는 동안 매 프레임 발동
	};

	//애니메이션
	enum class ANIM_NOTIFY_TYPE //바이너리화 안전하게 하려면 _int 명시적으로 해줘야한다고함.
	{NOTIFY //단일 시점 (특정 한 프레임에 1회성)
	,NOTIFY_STATE , END}; // 기간 설정(시작과 끝 지점 사이의 일정 기간동안 지속)
	enum class ANIM_EVENT_TYPE
	{PLAY_SOUND, SPAWN_PARTICLE, ACTIVE_COLLIDER, CAMERA, SPAWN_TRAIL, PLAYER_ANIM, MONSTER_ANIM, DISSOLVE_FLAG, END};
	enum class ANIM_FRAMEPHASE {START, UPDATE, END , ANIMFRAMEPHASE_END}; //애니메이션 패스 지정, Update는 매 프레임 호출하기 위해서
	// 엔진 타입
	enum class TOOLTYPE { MAP_TOOL, UI_TOOL, SHADER_TOOL, ANIMATION_TOOL, VFX_TOOL, TOOL_END };
	// 오브젝트 타입(파싱용)
	enum class OBJTYPE { TYPE_CHARACTER, TYPE_MAP, TYPE_CONTAINER, TYPE_PART, TYPE_EVENT, TYPE_END };
	/* Frustum-AABB 테스트 결과 3가지 */
	enum class FRUSTUM_RESULT : unsigned int
	{
		OUTSIDE,        // 완전히 밖
		INTERSECT,      // 걸쳐있음 자식 추가 테스트 필요
		FULLY_INSIDE,    // 완전히 안쪽, 자식 테스트 스킵
		END
	};
	typedef enum class StructuredBuffer_USAGE
	{
		IMMUTABLE,		// GPU 읽기 전용, 최초 1회 세팅
		DYNAMIC,		// CPU -> GPU 매 프레임 갱신 가능
		GPU_READWRITE,	// GPU 읽기/쓰기 (UAV), ComputeShader 결과 기록용
		END
	}SBUSAGE;

	enum class UI_MODE {DEFAULT,INVENTORY,SAVEPOINTMENU,BASE,END};
#pragma region UI
	enum class UITYPE { ROOT, IMAGE, BUTTON, PROGRESSBAR, ANIMATION, SPRITE, EVENTREACTOR, TEXT,BITMAPTEXT, WORLDUI,SLOTGRID,END };

	//UIEVENT TYPE ENUM
	enum class UI_EVENT_TARGET {
		COMPONENT,	//자신의 컴포넌트의 함수를 실행시키ㄱㅣ
		UIOBJECT,	//uioBJECT 의 함수실행시키기(오너)
		SYSTEM,		//전역적으로 관리하는 이벤트 실행시키기
		END
	};

#pragma endregion

	/* 트리거용 충돌 박스 */
	typedef enum class COLLISION_GROUP : unsigned int
	{ PLAYER, PLAYER_WEAPON, MONSTER, EVENT_POINT, SPAWN_TRIGGER, INTERACTION, ITEM, END }COLGROUP, COLTYPE; //콜리전 그룹
	typedef enum class CAMERA_ACTION { SHAKE, ZOOM_IN, ZOOM_OUT, CAMERAATCION_END } CAMACTION_TYPE; //카메라 이벤트시 무슨 액션 취할건지 


#pragma region PhysX
	// PhysX 전용 액터 분류(전투 시스템용)
	typedef enum class PHYSX_ACTOR_TYPE : PxU32
	{
		STATIC_MAP,         // 지형, 벽, 바닥
		DYNAMIC_MAP,		// 파괴 가능한 오브젝트
		PLAYER,             // 플레이어 CCT
		COMPANION,			// 동행자(야쿠모만 계획)
		MONSTER,            // 몬스터 CCT
		PLAYER_ATTACK,      // 플레이어 공격 판정 (Sweep/Overlap용)
		COMPANION_ATTACK,	// 동행자 공격 판정
		MONSTER_ATTACK,     // 몬스터 공격 판정
		PROJECTILE,			// 투사체
		BONE_CHAIN,
		END
	} PX_ACTOR_TYPE;
#pragma endregion PhysX

#pragma region PlayerAnimType
	enum class WEAPON_ANIM_ACTION //무기별 공통 애니메이션
	{
		IDLE,
		ATTACKNORMAL, //기본 마우스 좌클릭 공격 : 약공격
		ATTACKSTRONG, //기본 마우스 우클릭 공격 : 강공격
		SPECIALDOWN2, // 좌클릭 + Shift : 무기별 고유 액션
		SPECIALLAUNCH, //우클릭 + Shift : 무기별 고유 액션
		ATTACKDODGE_F, //키 입력 + Shift + 좌클릭or우클릭 / 구르고 나서 바로 좌클릭or 우클릭 : 대시 공격
		ATTACKDODGE_B, //백스텝(제자리 스페이스) + 좌클릭or우클릭
		DODGEROLL, //기본 구르기
		DODGEROLL_BACK, //가만히 있을때 뒤로 구르기
		GUARD_START, //가드 시작
		GUARD_LOOP, //가드 루프
		GUARD_END, //가드 끝
		GUARD_HIT, //가드시 히트(타격) 당했을때
		GUARD_BREAK, //가드상태에서 스태미나 없는데 히트 당했을때,
		ATTACKSTRONGCHARGE, //강공격 차징용
		END
	};
#pragma endregion

	enum class DAMAGEPOWER //몬스터 , 플레이어 공용 적용하고 싶은 모션 적용 / 해당 파워 타입에 따른 데미지 피격 모션 재생
	{
		NORMALPOWER, //약공격 (플레이어 : 기본피격)
		STRONGPOWER, //강공격 (플레이어 : 강한피격)
		HEAVYPOWER, //헤비공격 (플레이어 : 날아가는 모션)
		SPECIALPOWER, //스페셜 공격(플레이어 : 제자리 넘어지는 모션)
		STUNPOWER, // 스턴 공격 (플레이어 : 패링 공격시 몬스터들 스턴상태)
		POWER_END,
	};

#pragma region EFFECT
	enum class EFFECTTYPE
	{
		EFFECT_PARTICLE,
		EFFECT_TRAIL,
		EFFECT_MESH,
		EFFECT_END
	};
#pragma endregion


	/* 풀링 대상 ID (배열 인덱스로 직접 사용) */
	/* 새 풀링 대상 추가 시 END 위에 한 줄 추가 */
	enum class POOL_ID : _uint
	{
		MONSTER_BEGIN,  // 몬스터 카테고리 시작

		MONSTER_STAGE01_BEGIN,  // 스테이지 1 카테고리 시작
		MONSTER_SLIME, MONSTER_SLAVE_DEVIL, MONSTER_SLAVE_VAMPIRE, MONSTER_OLIVER,
		MONSTER_STAGE01_END,    // 스테이지 1 카테고리 종료

		MONSTER_STATE02_BEGIN = MONSTER_STAGE01_END,	// 스테이지 2 카테고리 시작
		MONSTER_WOLFGHOST, MONSTER_GIANT_VAMPIRE, MONSTER_MONKEY_DEVIL,MONSTER_GIANT_WHITEDEVIL, MONSTER_GHOSTKNIGHT,
		MONSTER_STAGE02_END,							// 스테이지 2 카테고리 종료

		MONSTER_END,    // 몬스터 카테고리 종료

		EFFECT_BEGIN = MONSTER_END, // 이펙트 카테고리 시작

		EFFECT_PLAYER_SLASH,
		EFFECT_PLAYER_GUARD,
		EFFECT_HALBERD_DODGE,
		EFFECT_HEAL, EFFECT_YAKUMO_HEAL, EFFECT_USE_ITEM, EFFECT_ONCE_HEAL, EFFECT_ONCE_HEAL_AURA,
		EFFECT_BACKSTAB, EFFECT_BACKSTAB_HAND,
		EFFECT_SPECIALATK_BLOOD, EFFECT_SPECIALATK_BLOOD2,
		EFFECT_SKILL_ROYAL_HEART,
		EFFECT_SKILL_SA_AURA, EFFECT_SKILL_SA_BODY, EFFECT_SKILL_SA_HIT, EFFECT_SKILL_SA_SLASH, EFFECT_SKILL_SA_WIND,
		EFFECT_SKILL_BLADEDANCING,
		EFFECT_SKILL_KR_AURA, EFFECT_SKILL_KR_BODY1, EFFECT_SKILL_KR_BODY2, EFFECT_SKILL_KR_WIND, EFFECT_SKILL_KR_AFTERIMPACT,
		EFFECT_SKILL_KR_IMPACT, EFFECT_SKILL_KR_PARTICLES1, EFFECT_SKILL_KR_PARTICLES2,
		EFFECT_SKILL_RB_AURA, EFFECT_SKILL_RB_LASER, EFFECT_SKILL_RB_SHOT,
		EFFECT_SKILL_IC_HAND, EFFECT_SKILL_IC_THUNDER,
		EFFECT_SKILL_ENCHANT_HAND, EFFECT_SKILL_ENCHANT_WEAPON, EFFECT_SKILL_ENCHANT_PARTICLES,
		EFFECT_HIT,	EFFECT_HIT_BLOOD, EFFECT_HIT_FLAME,
		EFFECT_PLAYER_WALK, EFFECT_PLAYER_DODGE, EFFECT_STRONG_ATTACK_CHARGE, EFFECT_SKILL_STRIKE_RISER, EFFECT_SKILL_STRIKE_RISER_HAND,
		EFFECT_SHOTGUN, EFFECT_SHOTGUN_BARREL, EFFECT_SHOTGUN_BULLET, EFFECT_SHOTGUN_CIRCLE, EFFECT_SHOTGUN_CIRCLE_SMOKE,
		EFFECT_ENEMY_SLASH, EFFECT_ENEMY_ATK_IMPACT, EFFECT_ENEMY_ATK_IMPACTNEW, EFFECT_ENEMY_FIELDSPLASH, EFFECT_ENEMY_SHIELD_RED,

		EFFECT_OLIVER_SLASH, EFFECT_OLIVER_TRANSITION, EFFECT_OLIVER_SPECIALATK, EFFECT_OLIVER_SPECIALATK_HAND, EFFECT_OLIVER_SCREAM,
		EFFECT_WOLF_BLOODBOOM_PLATE, EFFECT_WOLF_BLOODBOOM_PILLAR, EFFECT_WOLF_BLOODBOOM_HAND, 
		EFFECT_WOLF_FIREBLAST_ATTACK, EFFECT_WOLF_FIREBLAST_MAIN, EFFECT_WOLF_FIREBLAST_HAND, EFFECT_WOLF_FIREBLAST_PLATE, EFFECT_WOLF_FIRE_HELLFIREBULLET, EFFECT_WOLF_FIRE_HELLFIREBULLET_HIT, EFFECT_WOLF_FIRE_HELLFIREBULLET_HAND, EFFECT_WOLF_FIRE_HELLFIREBULLET_HAND_SHOKE,
		EFFECT_WOLF_THUNDER_HAND_CIRCLE, EFFECT_WOLF_THUNDER_HAND_AURA, EFFECT_WOLF_THUNDER_PLATE, EFFECT_WOLF_THUNDER_PILLAR, EFFECT_WOLF_THUNDER_BULLET, EFFECT_WOLF_THUNDER_GATE, EFFECT_WOLF_THUNDER_GATE_END, EFFECT_WOLF_THUNDER_GATE_BLINK, EFFECT_WOLF_THUNDER_BULLET_HIT,
		EFFECT_WOLF_ICE_HAND, EFFECT_WOLF_ICE_BULLET, EFFECT_WOLF_ICE_HOMING_BULLET, EFFECT_WOLF_ICE_HOMING_HIT,
		EFFECT_WOLF_VOIDLASER, EFFECT_WOLF_VOIDLASER_SMOKE,
		EFFECT_WOLF_SOLARLASER, EFFECT_WOLF_SOLARLASER_PARTICLE,
		EFFECT_WOLF_TP_BOTTOM, EFFECT_WOLF_TP_START, EFFECT_WOLF_TP_FLAME, EFFECT_WOLF_TP_END,
		EFFECT_WHITEDEVIL_TRANSITION, EFFECT_WHITEDEVIL_AURA, EFFECT_WHITEDEVIL_SLASH,
		EFFECT_GHOSTKNIGHT_PARTICLE, EFFECT_GHOSTKNIGHT_ATK,
		EFFECT_MISTLE, EFFECT_FIRE, EFFECT_GROUND_ITEM,
		EFFECT_FOCUS,
		EFFECT_DEATH_PARTICLE,
		EFFECT_DISSOLVE_PARTICLE,

		EFFECT_END,                 // 이펙트 카테고리 종료


		PROJECTILE_BEGIN = EFFECT_END,   // 투사체 시작
		BAYONET_BULLET, //바요네트 무기 총알
		INDRACOIL_THUNDER, //인드라 코일 스킬 번개
		HOMING_HEAL, //힐 투사체
		PROJECTILE_WOLFGHOST_ATTACK, PROJECTILE_MONSTER_DIRECT, PROJECTILE_MONSTER_HOMING, PROJECTILE_WOLFGHOST_ICE, PROJECTILE_WOLFGHOST_EFFECT,

		PROJECTILE_END,     // 투사체 종료

		ITEM_BEGIN = PROJECTILE_END, 
		ITEM_GROUND,
		ITEM_DROP,
		ITEM_END,

		END
	};

	/* 포화 정책: 풀이 꽉 찼을 때 어떻게 할 것인가 */
	enum class POOL_POLICY
	{
		DENY,              /* 거부: 실패 반환 */
		RECYCLE_OLDEST,    /* 가장 오래된 활성 오브젝트를 강제 회수 후 재사용 */
		GROW,              /* 배치 단위로 추가 Clone */
		END
	};

	// Ease 보간 타입
	enum class EASE_TYPE
	{
		LINEAR,
		SMOOTHSTEP,
		SMOOTHERSTEP,
		EASE_IN_QUAD,
		EASE_OUT_QUAD,
		EASE_IN_OUT_QUAD,
		EASE_IN_CUBIC,
		EASE_OUT_CUBIC,
		EASE_IN_OUT_CUBIC,
		EASE_OUT_ELASTIC,
		EASE_OUT_BACK,
		EASE_OUT_BOUNCE,
		EASE_END
	};

}
#endif // Engine_Enum_h__